services:
  nextjs:
    build: ./
    image: nextjs:latest
    container_name: nextjs
    restart: always
    expose:
      - 3000
    env_file:
      - /.env
  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    depends_on:
      - nextjs