services:
  nextjs:
    build: ./
    image: nextjs:latest
    container_name: nextjs
    restart: always
    expose:
      - 3000
    env_file:
      - /.env
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - nextjs